name: Build and Push Docker Image


on:
  push:
    branches:

      - Project-Heimir-2


jobs:
  build:
    runs-on: ubuntu-latest
    env:

      project: "project-heimir"
      architecture: "linux/arm64"

    steps:

      - name: Evaluate Commit Message
        run: |

          commitMessage="${{ github.event.head_commit.message }}";

          if [ "$commitMessage" != "Update" ]; then

             echo "Cancelling Workflow.";
             exit 1;

          fi

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: ${{ env.architecture }}
          tags: ${{ secrets.DOCKERHUBUSERNAME }}/${{ env.project }}:latest